#import "../meta.typ": acr-emph, acrpl-emph, note, tab-d, tab-h
#import "@preview/acrostiche:0.7.0": acr, acrpl

= Stand der Technik <stand-der-technik>

#acr("TSN") hat sich als herstellerübergreifender Ansatz etabliert, um deterministische Kommunikation auf Standard-Ethernet abzubilden @zhang2024tsn. Die dafür grundlegende Zeitsynchronisation ist in IEEE 802.1AS spezifiziert, einschließlich der Zielgröße einer #acr-emph("E2E")-Synchronisationsgenauigkeit von $<=1mu s$ über bis zu sieben Hops @ieee8021as2025[B.3]. Der Standard beschreibt jedoch nur das geforderte Verhalten. Ob eine konkrete Implementierung dies auch zeigt, lässt sich nur durch Messungen validieren.

Für dedizierte #acr("TSN")-Hardware liegen entsprechende Messungen bereits vor. Bailleul et al. vermessen vier #acr("TSN")-Switches in einer Kettentopologie und erfassen die Abweichung jedes Knotens zur Grandmaster Clock über deren #acr-emph("PPS")-Signale, die gegen eine GNSS-gestützte Referenzuhr ausgewertet werden @bailleul2022erts. Die dort über drei Hops gemessenen Offsets bleiben im Nanosekundenbereich und damit deutlich innerhalb der normativen Grenze. Dass die Einhaltung des Standards auf dem Papier dabei keine Funktion im Gesamtsystem garantiert, zeigt sich in einem herstellerübergreifenden #acr("TSN")-Aufbau. Dort führten abweichende Auslegungen desselben Standards sowie inkonsistent gesetzte Parameter zu einem Verhalten, das die Synchronisation des Gesamtsystems beeinträchtigte @brunner2025crossvendor.

Für Embedded-Systeme stellt das Echtzeitbetriebssystem Zephyr einen vollständigen 802.1AS-Protokollstapel bereit @zephyr_gptp. Die Codebasis muss also nicht neu entwickelt, sondern lediglich in Betrieb genommen und bewertet werden. Für die Rolle des Endpunkts ist dies bereits geschehen: Riep implementiert und evaluiert einen #acr("gPTP")-Time-Receiver auf einem Mikrocontroller der NXP-i.MX-RT-Familie, die auch in dieser Arbeit als Bridge-Plattform zum Einsatz kommt @riep2025. Dabei wird der Zephyr-Stack um einen #acr-emph("PI")-Clock-Servo mit vorgeschalteter Normierungskomponente ergänzt. Die Synchronisationsgenauigkeit verbessert sich dadurch so weit, dass der Sub-Mikrosekundenbereich erreichbar wird. Gegenüber der etablierten Referenzimplementierung LinuxPTP bleibt der Zephyr-Stack in Stabilität und Genauigkeit jedoch deutlich zurück. Ergänzend traten Inkompatibilitäten gegenüber einzelnen kommerziellen Switches auf, die mit LinuxPTP an derselben Gegenstelle nicht auftraten @riep2025.

Damit ist der Zephyr-Stack bislang ausschließlich als Endpunkt vermessen. Auch die dortige Messung über mehrere Hops nutzt kommerzielle Switches als Zwischenknoten, während das Zephyr-Gerät am Ende der Kette verbleibt @riep2025. Die Rolle der Time-Aware Bridge, in der ein Gerät Synchronisationsnachrichten nicht nur empfängt, sondern unter Kompensation der eigenen Verarbeitungszeit weiterreicht, bleibt dabei unberührt. Der Zephyr-Stack implementiert diese Funktion zwar, führt sie in der Projektdokumentation jedoch ausdrücklich als nicht validiert @zephyr_gptp. Genau an dieser Stelle setzt die vorliegende Arbeit an. Sie validiert die Bridge-Funktionalität messtechnisch und über mehrere Hops hinweg, in denen die Zephyr-Geräte selbst die Zwischenknoten bilden.
