#import "../meta.typ": acr-emph, fig-platzhalter-mittel, note, req, tab-d
#import "@preview/acrostiche:0.7.0": acr, acrpl

= Analyse und Entwurf
Aufbauend auf den in Kapitel 2 vorgestellten Grundlagen leitet dieses Kapitel zunächst die für die vorliegende Arbeit relevanten Anforderungen an eine konforme #acr-emph("gPTP")-Implementierung ab. Anschließend wird der grundlegende Testaufbau vorgestellt, mit dem diese Implementierung in den folgenden Kapiteln validiert wird, gefolgt von der Messmethodik, die beschreibt, wie die Einhaltung der zuvor abgeleiteten Anforderungen messtechnisch nachgewiesen wird. Abschließend werden bekannte Ungenauigkeiten des Testaufbaus benannt, die bei der späteren Interpretation der Messergebnisse zu berücksichtigen sind.

== Anforderungen

Eine konforme #acr-emph("gPTP")-Implementierung muss mehr leisten, als nur die in Annex B des Standards genannten Zeitgrenzwerte einzuhalten. Dieser Abschnitt gliedert die für die Arbeit relevanten Anforderungen deshalb in vier Gruppen: die normativen Leistungsanforderungen aus Annex B selbst, die Robustheit der Synchronisierung unter Netzwerklast, die Ressourcenstabilität der Implementierung über die Messdauer hinweg, sowie die sich aus dem Testaufbau ergebenden Hardwareanforderungen.

=== Normative Leistungsanforderungen <normative-leistungsanforderungen>
Der Standard macht die Synchronisierung eines Ports von der Variable `asCapable` abhängig @ieee8021as2025[10.2.5.1]. Nur wenn sie `TRUE` ist, verarbeitet die Sync-Statemachine überhaupt eingehende Sync-Nachrichten @ieee8021as2025[11.2.2]. Ist sie `FALSE`, verwirft die Bridge jede Sync-Nachricht. Unter anderem hängt `asCapable` vom gemessenen meanLinkDelay ab @ieee8021as2025[11.2.2]. Überschreitet dieser $800n s$ (100BASE-TX/1000BASE-T), geht der Standard von Equipment ohne #acr("gPTP")-Unterstützung im Pfad aus und setzt `asCapable` auf `FALSE`.

Ist `asCapable` TRUE, hängt die tatsächlich erreichte Genauigkeit von zwei weiteren, unabhängigen Anforderungen ab. Die Granularität der LocalClock darf $40n s$ nicht überschreiten @ieee8021as2025[B.1.2], und die Messgenauigkeit der rateRatio muss innerhalb von $0.1$ #acr("ppm") liegen @ieee8021as2025[B.2.4]. Eine gröbere Granularität würde bereits die zugrundeliegenden Zeitstempel verfälschen, eine ungenauere rateRatio-Messung den #acr("PI")-geregelten Frequenzabgleich zwischen den Clocks.

Werden diese Anforderungen eingehalten, gilt die eigentliche Zielgröße dieser Arbeit. Die #acr-emph("E2E")-Synchronisationsgenauigkeit von $<=1mu s$ über bis zu sieben Hops @ieee8021as2025[B.3], allerdings ausdrücklich nur "during steady-state operation", was bedeutet, dass die Einschwingphase hier nicht beachtet wird @ieee8021as2025[B.3].

=== Robustheit unter Netzwerklast <anforderung-netzwerklast>
Annex B selbst nennt keinen eigenen Grenzwert für Netzwerklast. Relevant ist die Anforderung dennoch, weil die #acr-emph("E2E")-Synchronisationsgenauigkeit aus @normative-leistungsanforderungen laut Standard nur unter der bereits genannten Bedingung gilt, dass jede Instanz ihre Sync-Nachricht in jedem Intervall empfängt. Genau diese Bedingung gefährdet Best-Effort-Nutzverkehr auf demselben physischen Port. Werden #acr("gPTP")-Nachrichten durch konkurrierenden Verkehr verzögert oder verworfen, ist die Vorbedingung von B.3 verletzt, unabhängig davon, wie exakt Granularität und rateRatio-Genauigkeit eingehalten werden.

=== Ressourcenstabilität <anforderung-ressourcenstabilitaet>
Auch zur Ressourcenstabilität einer Implementierung trifft Annex B keine Aussage. Relevant ist sie dennoch, weil ein Synchronisationsausfall in der Praxis seltener durch einen einzelnen falschen Zeitstempel entsteht als durch Ressourcenerschöpfung. Volllaufende Empfangspuffer, überlaufende Zähler oder verlorene Referenzen, die sich erst nach längerer Laufzeit oder unter Last bemerkbar machen. Die Implementierung wird deshalb zusätzlich zur PPS-Messung über Hardware- und Software-Zähler beobachtet, die genau solche Fehler unabhängig vom Offset sichtbar machen.

=== Hardwareanforderungen

Neben den normativen Leistungsanforderungen ergeben sich aus dem gewählten Testaufbau weitere Anforderungen an die eingesetzte Hardware. Zeitstempel für ein- und ausgehende #acr("gPTP")-Nachrichten müssen dabei mindestens auf #acr("MAC")-Ebene erzeugt werden (siehe @hardware-timestamping), und jede Time-Aware Bridge muss Nachrichten an einem Port empfangen und über einen weiteren weiterleiten können, verfügt also über mindestens zwei Ports. Da im Testaufbau sowohl gigabit- als auch fast-ethernet-fähige Geräte in gemischten Ketten miteinander verbunden werden, muss außerdem jedes eingesetzte Gerät mindestens 100BASE-TX unterstützen, damit sich über alle Hops hinweg eine durchgängige Verbindung herstellen lässt.

== Grundlegender Testaufbau <testaufbau>
Für die nachfolgenden Tests werden drei phyBOARD-Atlas-Boards@phytec_imxrt1170_devkit als Bridge eingesetzt. Jedes Board verfügt über zwei Ethernet-Ports mit unterschiedlichem #acr("PHY"): Der 1GBit/s-Port nutzt einen #acr("PHY") mit #acr("SFD")-Erkennung @ti_dp83867e, der 100/10MBit/s-Port hingegen einen #acr("PHY") ohne #acr("SFD")-Erkennung @microchip_ksz8081. Des Weiteren werden zwei STM32H7-Boards@st_nucleo_h755zi_q eingesetzt, von denen eines als Grandmaster Clock und das andere als Endpoint fungieren soll. Beide verfügen ebenfalls über einen 10/100MBit/s-#acr("PHY") ohne #acr("SFD")-Erkennung. Durch diese Kombination lässt sich ein Testaufbau mit maximal vier Hops gestalten, was jedoch das Abschalten des #acr("BTCA") erzwingt, um den einzelnen Systemen ihre feste Rolle zuzuweisen.

Die beiden Ports des phyBOARD-Atlas weisen bei den in @mac-layer und @cbs behandelten #acr("CBS")-Mechanismen Unterschiede auf. Während die #acr("MAC")-Peripherie des 1GBit/s-Ports (`enet1g`) einen Credit Based Shaper unterstützt @zephyr_eth_nxp_enet_source, fehlt dem 100/10MBit/s-Port beider Geräte eine entsprechende Hardware-Warteschlange. Dies bedeutet, dass zwar alle Schnittstellen beider Geräte die Zeitsynchronisierung unterstützen, jedoch nur der enet1g-Port des phyBOARD-Atlas über geeignete Hardware für #acr("TSN")-Support im weiteren Sinne verfügt.

Zusätzlich verfügt jede Ethernet-Schnittstelle über einen eigenen #acr("MAC") und somit auch über eine eigene #acr("PTP")-Clock. Daher ist die relative Zeit von Port zu Port immer unterschiedlich. Im #acr("gPTP")-Stack wird allerdings immer nur die Clock zum zugehörigen Port synchronisiert. Dies führt dazu, dass der Master-Port auf der Bridge nicht synchronisiert ist und dadurch die nachfolgenden Systeme nicht korrekt synchronisieren kann. Um dieses Problem zu lösen, wird ein dedizierter Task in Zephyr erstellt, der sich um das Synchronisieren des Master-Ports zum Slave-Port auf der Bridge kümmert. Die Implementierung dieses Tasks beschreibt @bridge-sync-impl.

Da in dieser Arbeit ausschließlich die Bridgefunktion validiert werden soll, muss die als Grandmaster Clock eingesetzte Hardware selbst keine Anbindung an eine externe Referenzzeit besitzen und wird stattdessen im Free-Running-Mode betrieben. Alle übrigen Geräte synchronisieren sich wie in @tsn-intro beschrieben ausschließlich auf diese lokale Zeitbasis. Die dafür nötigen #acr("gPTP")-Nachrichten werden dabei nach den Standardwerten mit 1Hz für pDelay und 8Hz für Sync versendet.

== Messmethodik
Die zuvor abgeleiteten Anforderungen sind nur dann aussagekräftig, wenn sich ihre Einhaltung auch nachweisen lässt. Dieser Abschnitt beschreibt deshalb, mit welchen Verfahren die einzelnen Anforderungen am Testaufbau überprüft werden.

Den Kern bildet eine #acr("PPS")-basierte Messung, mit der sich der tatsächliche Zeitversatz zwischen den Clocks unabhängig vom #acr("gPTP")-Stack selbst messen lässt. Zunächst werden dazu der Messaufbau und die Datenerfassung vorgestellt. Da sich nicht alle Anforderungen über den #acr("PPS")-Offset abbilden lassen, werden anschließend die eigenständigen Nachweisverfahren für die rateRatio-Genauigkeit und die Ressourcenstabilität beschrieben. Abschließend wird festgelegt, wie die aufgenommenen Offset-Zeitreihen statistisch ausgewertet werden und ab wann eine Anforderung als erfüllt gilt.

=== Messaufbau und Datenerfassung
Um die tatsächlich erreichte Synchronisierungsgenauigkeit des Testaufbaus zu überprüfen, reicht eine rein softwareseitige Betrachtung der berechneten Offsets nicht aus, da diese bereits durch den Synchronisierungsalgorithmus korrigiert werden. Zudem würden systematische Messfehler innerhalb eines Controllers auf diese Weise nicht auffallen, da dieselben Fehler sowohl die #acr("gPTP")-Synchronisation selbst als auch eine rein softwareseitige Messung ihrer Genauigkeit gleichermaßen verfälschen würden. Stattdessen wird die Synchronisierung über einen unabhängigen Hardware-Trigger am jeweiligen Mikrocontroller nachgewiesen: Die zu vergleichenden Clocks legen jeweils ein #acr("PPS")-Signal auf einen #acr-emph("GPIO")-Pin. Ein Impuls, der immer genau beim Rollover zur nächsten Sekunde ausgelöst wird. Da dieser Impuls direkt aus dem internen Timer der Clock abgeleitet wird, ist er unabhängig vom #acr("gPTP")-Stack. Die zeitliche Differenz zweier #acr("PPS")-Flanken entspricht dem tatsächlichen Offset zwischen den beiden Clocks und lässt sich extern messen@nguyen2020fuzzypi.

Für die Erfassung wird ein Oszilloskop mit vier Kanälen eingesetzt. Einer dieser Kanäle ist in jeder Messung fest dem #acr("GM") zugeordnet, da deren Clock die Referenz ist, auf die sich alle übrigen Geräte synchronisieren. Die verbleibenden drei Kanäle werden je nach Messziel unterschiedlich belegt.

Da das Oszilloskop selbst zur Messkette gehört, muss dessen zeitliche Auflösung deutlich feiner sein als die kleinste zu prüfende Anforderung. Andernfalls würde die Quantisierung des Messgeräts das Messergebnis verfälschen, statt es nur abzubilden. Das eingesetzte Oszilloskop muss folglich eine Zeitbasis im niedrigen Nanosekundenbereich auflösen, damit die $40n s$-Anforderung überhaupt nachweisbar ist. Zum Einsatz kommt ein Keysight MSOX3104T@keysight_msox3104t mit $1"GHz"$ Bandbreite und einer Abtastrate von $5"GSa/s"$, was einem zeitlichen Abstand von $200p s$ zwischen zwei Samples entspricht und damit deutlich unterhalb der geforderten $40n s$ liegt.

Die #acr("PPS")-Flanken der belegten Kanäle werden dabei jeweils gleichzeitig über eine Länge von 1000 #acr("PPS")-Perioden aufgenommen und als Rohdaten exportiert. Ein Auswertungsskript berechnet aus jedem erfassten Flankensatz sowohl den Offset jedes Kanals relativ zum #acr("GM") als auch die Differenz zwischen benachbarten Kanälen (Hop-zu-Hop-Offset). Welche der beiden Größen im Vordergrund steht, hängt vom jeweiligen Messziel ab. Der #acr("GM")-relative Offset weist die kumulative #acr-emph("E2E")-Synchronisationsgenauigkeit der gesamten Kette nach, während der Hop-zu-Hop-Offset den Beitrag einer einzelnen Bridge isoliert und damit erlaubt, Effekte wie die #acr-emph("PHY")-Asymmetrie aus @Ungenauigkeiten einer konkreten Bridge zuzuordnen. Für jeden Offset ergibt sich damit eine Zeitreihe über die gesamte Messdauer, die als Diagramm über der Zeit dargestellt wird.

In diesen Diagrammen ist unabhängig vom Messziel ein charakteristischer Verlauf zu erwarten. Direkt nach dem Start bzw. Link-Up ist der Offset zwischen den Clocks zunächst groß, da noch keine Synchronisierung stattgefunden hat. Mit fortschreitender Regelung durch den Synchronisierungsalgorithmus sinkt der Offset über mehrere Sync-Intervalle hinweg, bis er in einen stabilen Zustand übergeht. Dieser Einschwingvorgang macht die Regelung des Synchronisierungsalgorithmus sichtbar. Der Offset läuft dabei nicht exakt gegen null, sondern pendelt im eingeschwungenen Zustand innerhalb eines kleinen Reststreubands. Für den #acr("GM")-relativen Offset ist dessen maximal zulässige Breite direkt durch die #acr-emph("E2E")-Synchronisationsgenauigkeit aus @normative-leistungsanforderungen vorgegeben.

Neben der PPS-Messung existiert für Anforderungen, die sich nicht allein über den PPS-Offset nachweisen lassen, eine zweite Datenerfassung. Über die UART-Shell von Zephyr lassen sich Logs aufzeichnen, welche mehr Details über das System preisgeben. Das Logging läuft dabei über die gesamte Laufzeit mit und liefert Daten, die für den jeweiligen Nachweis eine genauere oder unabhängige Aussage erlauben. Welche Daten das im Einzelnen sind und wie sie ausgewertet werden, wird in den jeweiligen Abschnitten @nachweis-rateratio und @nachweis-ressourcenstabilitaet beschrieben.

=== Kanalbelegung je Messziel <kanalbelegung>
Welche Messpunkte auf die drei frei belegbaren Kanäle gelegt werden, richtet sich nach der Länge der zu vermessenden Kette.

Bei einer einzelnen Bridge genügt ein Lauf für beide Größen: Belegt man die Kanäle mit #acr("GM"), Slave-Port und Master-Port derselben Bridge sowie dem Endpoint, liefert derselbe Flankensatz sowohl den #acr("GM")-relativen Offset jedes Messpunkts als auch den isolierten Hop-zu-Hop-Offset dieser Bridge. Letzterer steht dabei im Vordergrund, unabhängig davon, an welcher Stelle der Kette die Bridge später eingesetzt wird.

Sobald mehr als eine Bridge im System ist, reichen vier Kanäle nicht mehr aus, um die gesamte Kette gleichzeitig zu erfassen. Da die #acr-emph("E2E")-Synchronisationsgenauigkeit laut Standard aber kumulativ über die Kette gilt und der Testaufbau mit maximal vier Hops innerhalb der zulässigen sieben bleibt, wird die Kette in mehreren Läufen mit wechselnder Kanalbelegung durchgemessen. Die Kanäle für #acr("GM") und Endpoint bleiben dabei über alle Läufe fest belegt, sodass sich die Läufe über diese gemeinsame Referenz zusammenführen lassen. Im Vordergrund steht hier entsprechend der #acr("GM")-relative Offset.

=== Nachweis der rateRatio-Genauigkeit <nachweis-rateratio>
Die #acr("PPS")-Messung weist die #acr-emph("E2E")-Synchronisationsgenauigkeit nach, eignet sich aber nicht für den Nachweis der rateRatio-Genauigkeit aus @ieee8021as2025[B.2.4] - unter anderem gefordert für den internen Abgleich zwischen Master- und Slave-Instanz der Bridge (siehe @bridge-sync-impl). Da rateRatio eine Frequenzgröße ist, wird dieser Nachweis stattdessen über die Allan-Abweichung der geloggten rateRatio-Werte erbracht @allan1966statistics @riley2008frequencystability[13]. In dieser Arbeit wird dazu wie folgt vorgegangen:

1. Einschwingzeit abwarten, damit sich der #acr("PI")-Regler auf einen stabilen Zustand einschwingen kann.

2. rateRatio zwischen Master und Slave über einen definierten Zeitraum messen und loggen.

3. Aus den Messungen wird die Abweichung von der geforderten Genauigkeit geprüft, indem die Allan-Abweichung $sigma_y (tau)$ der rateRatio-Messreihe berechnet wird. Da rateRatio bereits eine über das Messintervall $tau$ gemittelte Frequenzschätzung ist, wird dazu die Varianz der Differenzen aufeinanderfolgender Werte gebildet, statt die Streuung um den Gesamtmittelwert zu betrachten wie bei der klassischen Standardabweichung: Für die bei Quarzoszillatoren typischen Rauschprozesse (z. B. Flicker- oder Random-Walk-Frequenzrauschen) konvergiert die klassische Varianz nicht zuverlässig und wird durch langsamen Drift verfälscht, während die Allan-Varianz dagegen robust ist @allan1966statistics – dasselbe Konzept (ADEV), das @ieee8021as2025[B.1.3.2] für die Rauschcharakterisierung der LocalClock referenziert @riley2008frequencystability[14]:

$
  sigma_y (tau) = sqrt(1/(2(M-1)) sum_(i=1)^(M-1) (y_(i+1) - y_i)^2)
$

Dabei ist $y_i = "rateRatio"_i - 1$ die fraktionale Frequenzabweichung des $i$-ten Messintervalls und $M$ die Anzahl der gemessenen Intervalle. Liegt die berechnete Allan-Abweichung $sigma_y (tau)$ innerhalb der geforderten 0,1 #acr("ppm"), gilt die Anforderung als erfüllt.

=== Nachweis der Ressourcenstabilität <nachweis-ressourcenstabilitaet>
Auch die in "Ressourcenstabilität" begründete Anforderung wird nicht über den PPS-Offset geprüft, sondern über zwei Zähler, die parallel zur Langzeitmessung sekündlich mitgeloggt werden. Die MAC-eigenen Statistikzähler (`rx_pkts`, `rx_ok`, `drop`, `crc`, `align`, `macerr`), die über `ENET_GetStatistics()` ausgelesen werden, sowie ein treiberinterner Zähler für fehlgeschlagene Pufferallokationen auf dem #acr("gPTP")-Empfangspfad (`alloc_fail_ptp`).

Anders als beim Nachweis über $t_"set"$ gibt es hier kein Einschwingverhalten und kein Toleranzband. Ausschlaggebend ist `alloc_fail_ptp`. Bleibt dieser treiberinterne, gPTP-spezifische Zähler über die gesamte Laufzeit bei null, gilt die Anforderung als erfüllt. Ein Anstieg der übrigen, globalen MAC-Zähler (`drop`, `crc`, `align`, `macerr`) ist dagegen kein eigenständiger Verstoß. Sie unterscheiden nicht nach Verkehrsklasse und dürfen unter Last durch verworfenen Best-Effort-Verkehr durchaus ansteigen, solange davon ausschließlich der unkritische Verkehr betroffen ist und weder `alloc_fail_ptp` noch die PPS-basierte Synchronisationsgenauigkeit sich dadurch verschlechtern.

=== Statistische Auswertung
Aus den Offset-Zeitreihen der PPS-basierten Validierungsszenarien werden für das Kapitel Evaluation zwei Aspekte abgeleitet. Der eigentliche Nachweis, dass die #acr-emph("E2E")-Synchronisationsgenauigkeit aus @normative-leistungsanforderungen eingehalten wird - im Netzwerklast-Test zugleich der Nachweis, dass die in @anforderung-netzwerklast begründete Vorbedingung dafür auch unter Last erfüllt bleibt -, sowie eine Beschreibung des eingeschwungenen Zustands, auf die dort bei der Diskussion der in @Ungenauigkeiten benannten Fehlerquellen zurückgegriffen wird. Die rateRatio-Genauigkeit und die Ressourcenstabilität werden dagegen über die in @nachweis-rateratio und @nachweis-ressourcenstabilitaet beschriebenen, eigenständigen Verfahren nachgewiesen.

*Läufe und Auswertungsintervalle*\
Ein einzelner Oszilloskop-Lauf ist auf 1000 #acr("PPS")-Perioden begrenzt (siehe "Messaufbau und Datenerfassung"), also rund 16,6 Minuten. Einzelbridge-Validierung, Kettenvalidierung und Netzwerklast-Test bleiben innerhalb dieses Fensters und liefern damit je eine durchgehende Zeitreihe pro Lauf. Die mehrstündige Langzeitmessung überschreitet dieses Fenster dagegen zwangsläufig und wird stattdessen durch mehrere über die Messdauer verteilte Läufe abgedeckt. Innerhalb eines Laufs kann es zudem mehrere Test-Cases geben, etwa die drei Laststufen in @netzwerklast-test. Die folgende Auswertung bezieht sich deshalb nicht auf den Lauf als Ganzes, sondern auf das jeweilige Auswertungsintervall. Bei einem Lauf mit nur einem Test-Case ist das der gesamte gültige Bereich nach $t_"set"$, bei mehreren Laststufen je Laststufe, bei der Langzeitmessung je Lauf.

*Nachweis*\
Die Anforderung aus @normative-leistungsanforderungen gilt als erfüllt, sobald eine Einschwingzeit $t_"set"$ existiert. Der früheste Zeitpunkt, ab dem der Offset das dadurch vorgegebene $1mu s$-Toleranzband nicht mehr verlässt und darin bis zum Ende des Laufs verbleibt. Eine einzelne, kurzzeitige Unterschreitung des Toleranzbands zählt nicht als Einschwingen, da sie nur zufällig getroffen sein kann. Bei der aus mehreren Läufen zusammengesetzten Langzeitmessung wird $t_"set"$ aus dem ersten Lauf bestimmt. Jeder folgende Lauf muss zusätzlich vollständig innerhalb des Toleranzbands liegen. Verlässt der Offset das Band in einem späteren Lauf erneut, obwohl $t_"set"$ bereits erreicht war, gilt die Anforderung als nicht erfüllt.

*Vergleichende Darstellung*\
Innerhalb eines Auswertungsintervalls werden die Messpunkte als Boxplots nebeneinander dargestellt. Median, Interquartilsabstand und Ausreißer sind darin für jeden Messpunkt auf einen Blick vergleichbar, ohne die einzelnen Offset-Zeitreihen übereinanderlegen zu müssen. Ein kurzzeitiger Paketverlust fällt so als einzelner Ausreißer auf. Bei Läufen mit mehreren Auswertungsintervallen lässt sich dieselbe Darstellung zusätzlich nutzen, um einen Messpunkt über die Intervalle hinweg zu vergleichen und so einen systematischen Trend von Median oder Streuung sichtbar zu machen.

Jedes Auswertungsintervall muss dabei lang genug sein, um nach $t_"set"$ noch mehrere hundert #acr("PPS")-Perioden für die Statistik zu liefern, damit Median, Interquartilsabstand und die übrigen Boxplot-Kennzahlen nicht mehr nennenswert vom Stichprobenumfang abhängen.

== Ungenauigkeiten<Ungenauigkeiten>
Der pDelay-Mechanismus aus @pDelay-mechanism setzt voraus, dass die Signallaufzeit zwischen zwei Ports in beide Richtungen symmetrisch ist @ieee8021as2025[11.2]. Nur unter dieser Annahme lässt sich aus der Summe $t_4 - t_1$ und $t_3 - t_2$ ein einseitiger meanLinkDelay berechnen. Der vorliegende Testaufbau verletzt jedoch diese Annahme. Wie in @testaufbau beschrieben, verfügt der 1Gbit #acr("PHY") über eine #acr("SFD")-Erkennung. Die beiden 10/100Mbit #acrpl("PHY") besitzen diese Funktion jedoch nicht. Alles, was in einem Ethernet-Frame vor dem #acr("SFD") steht, liegt dadurch innerhalb des Zeitstempels. Zusätzlich ist diese interne Verarbeitungszeit zwischen Sende- und Empfangsrichtung nicht notwendigerweise gleich groß, wodurch die Symmetrieannahme des pDelay-Mechanismus zusätzlich verletzt wird. Diese Asymmetrie erklärt, warum an Hops mit einem 10/100Mbit #acr("PHY") ein deutlich höherer meanLinkDelay gemessen wird.
